#!/usr/bin/env python3
"""
Patcher Métro-Taxi — Ajoute le système de broadcast 'Lancement Saint-Denis 13 juin 2026'.

Modifications :
1. backend/services/emails.py : ajoute send_launch_announcement_email()
2. backend/routes/admin.py    : ajoute import asyncio, import send_launch_announcement_email,
                                + 3 endpoints /admin/broadcast/launch-saint-denis/{preview,test,confirm}

Idempotent : si déjà patché, ne fait rien.
"""
import base64
import os
import sys
from datetime import datetime

PROJECT_ROOT = "/var/www/metro-taxi-app"
EMAILS_FILE = os.path.join(PROJECT_ROOT, "backend/services/emails.py")
ADMIN_FILE  = os.path.join(PROJECT_ROOT, "backend/routes/admin.py")

# Code à insérer (encodé en base64 pour zéro problème de caractères)
NEW_FUNCTION_B64 = """IyA9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PQojIEJST0FEQ0FTVCBMQU5DRU1FTlQgU0FJTlQtREVOSVMgMTMgSlVJTiAyMDI2CiMgPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0KYXN5bmMgZGVmIHNlbmRfbGF1bmNoX2Fubm91bmNlbWVudF9lbWFpbChlbWFpbDogc3RyLCBuYW1lOiBzdHIsIHBpb25lZXJfbnVtYmVyOiBpbnQgPSBOb25lKToKICAgICIiIkVtYWlsIGQnYW5ub25jZSBvZmZpY2llbGxlIGR1IGxhbmNlbWVudCBTYWludC1EZW5pcyAoMTMganVpbiAyMDI2KSBhdXggMzMgY2hhdWZmZXVycyBwaW9ubmllcnMuIiIiCiAgICBpZiBub3QgUkVTRU5EX0FQSV9LRVk6CiAgICAgICAgbG9nZ2luZy53YXJuaW5nKCJSRVNFTkRfQVBJX0tFWSBub3QgY29uZmlndXJlZCwgbGF1bmNoIGFubm91bmNlbWVudCBlbWFpbCBOT1Qgc2VudCIpCiAgICAgICAgcmV0dXJuIEZhbHNlCgogICAgcGlvbmVlcl9iYWRnZSA9IGYiUElPTk5JRVIgI3twaW9uZWVyX251bWJlcn0iIGlmIHBpb25lZXJfbnVtYmVyIGVsc2UgIkNIQVVGRkVVUiBQSU9OTklFUiIKICAgIHBpb25lZXJfbGluZSA9IGYiVHUgZXMgPHN0cm9uZyBzdHlsZT0nY29sb3I6I0ZGRDYwQSc+Y2hhdWZmZXVyIHBpb25uaWVyICN7cGlvbmVlcl9udW1iZXJ9PC9zdHJvbmc+IOKAlCB0dSBmYWlzIHBhcnRpZSBkZXMgMzMgdmlzYWdlcyBxdWkgdm9udCBpbmNhcm5lciBjZXR0ZSBvdXZlcnR1cmUuIiBpZiBwaW9uZWVyX251bWJlciBlbHNlICJUdSBlcyB1biBkZSBub3MgPHN0cm9uZyBzdHlsZT0nY29sb3I6I0ZGRDYwQSc+Y2hhdWZmZXVycyBwaW9ubmllcnM8L3N0cm9uZz4g4oCUIHR1IGZhaXMgcGFydGllIGRlcyAzMyB2aXNhZ2VzIHF1aSB2b250IGluY2FybmVyIGNldHRlIG91dmVydHVyZS4iCgogICAgaHRtbF9jb250ZW50ID0gZiIiIgo8IURPQ1RZUEUgaHRtbD4KPGh0bWw+PGhlYWQ+PG1ldGEgY2hhcnNldD0iVVRGLTgiPjwvaGVhZD4KPGJvZHkgc3R5bGU9ImZvbnQtZmFtaWx5OkhlbHZldGljYSxBcmlhbCxzYW5zLXNlcmlmO2JhY2tncm91bmQ6IzBhMGEwYTttYXJnaW46MDtwYWRkaW5nOjMwcHggMjBweDtjb2xvcjojZmZmOyI+CiAgPGRpdiBzdHlsZT0ibWF4LXdpZHRoOjYyMHB4O21hcmdpbjowIGF1dG87YmFja2dyb3VuZDojMWExYTFhO2JvcmRlci1yYWRpdXM6MTJweDtvdmVyZmxvdzpoaWRkZW47Ym9yZGVyLXRvcDo2cHggc29saWQgI0ZGRDYwQTsiPgoKICAgIDxkaXYgc3R5bGU9ImJhY2tncm91bmQ6I0ZGRDYwQTtwYWRkaW5nOjI4cHggMjRweDt0ZXh0LWFsaWduOmNlbnRlcjsiPgogICAgICA8cCBzdHlsZT0ibWFyZ2luOjAgMCA2cHggMDtjb2xvcjojMDAwO2ZvbnQtc2l6ZToxMnB4O2ZvbnQtd2VpZ2h0OmJvbGQ7bGV0dGVyLXNwYWNpbmc6MnB4OyI+e3Bpb25lZXJfYmFkZ2V9PC9wPgogICAgICA8aDEgc3R5bGU9Im1hcmdpbjowO2NvbG9yOiMwMDA7Zm9udC1zaXplOjI2cHg7bGV0dGVyLXNwYWNpbmc6LTFweDsiPvCfmpYgWk9ORSBTQUlOVC1ERU5JUzwvaDE+CiAgICAgIDxwIHN0eWxlPSJtYXJnaW46OHB4IDAgMCAwO2NvbG9yOiMwMDA7Zm9udC1zaXplOjE0cHg7Zm9udC13ZWlnaHQ6Ym9sZDsiPk9VVkVSVFVSRSBPRkZJQ0lFTExFIOKAlCBWRU5EUkVESSAxMyBKVUlOIDIwMjY8L3A+CiAgICA8L2Rpdj4KCiAgICA8ZGl2IHN0eWxlPSJwYWRkaW5nOjM2cHggMzBweDsiPgogICAgICA8aDIgc3R5bGU9ImNvbG9yOiNGRkQ2MEE7Zm9udC1zaXplOjIycHg7bWFyZ2luOjAgMCAxOHB4IDA7Ij5Cb25qb3VyIHtuYW1lfSDwn5GLPC9oMj4KCiAgICAgIDxwIHN0eWxlPSJjb2xvcjojZTRlNGU3O2xpbmUtaGVpZ2h0OjEuNztmb250LXNpemU6MTVweDttYXJnaW46MCAwIDE2cHggMDsiPgogICAgICAgIEMnZXN0IG9mZmljaWVsIDogPHN0cm9uZyBzdHlsZT0iY29sb3I6I0ZGRDYwQSI+dmVuZHJlZGkgMTMganVpbiAyMDI2PC9zdHJvbmc+LCBNw6l0cm8tVGF4aSBvdXZyZSBzYSA8c3Ryb25nPnByZW1pw6hyZSB6b25lIHBpbG90ZSBwYXlhbnRlIMOgIFNhaW50LURlbmlzPC9zdHJvbmc+ICg5MykuCiAgICAgIDwvcD4KCiAgICAgIDxwIHN0eWxlPSJjb2xvcjojZTRlNGU3O2xpbmUtaGVpZ2h0OjEuNztmb250LXNpemU6MTVweDttYXJnaW46MCAwIDI0cHggMDsiPgogICAgICAgIHtwaW9uZWVyX2xpbmV9CiAgICAgIDwvcD4KCiAgICAgIDxoMyBzdHlsZT0iY29sb3I6I0ZGRDYwQTtmb250LXNpemU6MTZweDttYXJnaW46MjhweCAwIDEycHggMDtib3JkZXItYm90dG9tOjFweCBzb2xpZCAjMjcyNzJhO3BhZGRpbmctYm90dG9tOjhweDsiPuKaoSBDZSBxdWkgdmEgc2UgcGFzc2VyIGxlIDEzIGp1aW48L2gzPgogICAgICA8dWwgc3R5bGU9ImNvbG9yOiNjY2NjY2M7bGluZS1oZWlnaHQ6MS44O2ZvbnQtc2l6ZToxNHB4O21hcmdpbjowIDAgMThweCAwO3BhZGRpbmctbGVmdDoyMHB4OyI+CiAgICAgICAgPGxpPk91dmVydHVyZSBkZXMgPHN0cm9uZz5hYm9ubmVtZW50cyB1c2FnZXJzPC9zdHJvbmc+IHBvdXIgbGEgem9uZSBTYWludC1EZW5pczwvbGk+CiAgICAgICAgPGxpPkxlcyA8c3Ryb25nIHN0eWxlPSJjb2xvcjojRkZENjBBIj4zMCBwcmVtaWVycyBhYm9ubsOpczwvc3Ryb25nPiByZWNldnJvbnQgYXV0b21hdGlxdWVtZW50IHVuZSA8c3Ryb25nPnByZW1pw6hyZSBjb3Vyc2Ugb2ZmZXJ0ZSAo4omkIDEwIGttKTwvc3Ryb25nPjwvbGk+CiAgICAgICAgPGxpPjxzdHJvbmc+VG9pPC9zdHJvbmc+LCB0dSBjb21tZW5jZXMgw6AgcmVjZXZvaXIgZGVzIGNvdXJzZXMgZMOocyBsZSBwcmVtaWVyIGFib25uw6kgYWN0aWYgZGFucyB0YSB6b25lPC9saT4KICAgICAgPC91bD4KCiAgICAgIDxoMyBzdHlsZT0iY29sb3I6I0ZGRDYwQTtmb250LXNpemU6MTZweDttYXJnaW46MjhweCAwIDEycHggMDtib3JkZXItYm90dG9tOjFweCBzb2xpZCAjMjcyNzJhO3BhZGRpbmctYm90dG9tOjhweDsiPvCfkrAgVG9uIG1vZMOobGUgKGlsIG5lIGNoYW5nZSBwYXMpPC9oMz4KICAgICAgPHRhYmxlIHdpZHRoPSIxMDAlIiBjZWxscGFkZGluZz0iMCIgY2VsbHNwYWNpbmc9IjAiIHN0eWxlPSJiYWNrZ3JvdW5kOiMwYTBhMGE7Ym9yZGVyLXJhZGl1czo4cHg7Ym9yZGVyLWxlZnQ6NHB4IHNvbGlkICNGRkQ2MEE7bWFyZ2luOjAgMCAxOHB4IDA7Ij4KICAgICAgICA8dHI+PHRkIHN0eWxlPSJwYWRkaW5nOjE4cHggMjBweDsiPgogICAgICAgICAgPHAgc3R5bGU9ImNvbG9yOiNmZmY7bWFyZ2luOjAgMCA4cHggMDtmb250LXNpemU6MTRweDsiPuKchSA8c3Ryb25nPjEsNTAg4oKsIC8ga20gcGFyY291cnU8L3N0cm9uZz4gYXZlYyBhdSBtb2lucyB1biBhYm9ubsOpIE3DqXRyby1UYXhpIMOgIGJvcmQ8L3A+CiAgICAgICAgICA8cCBzdHlsZT0iY29sb3I6I2ZmZjttYXJnaW46MCAwIDhweCAwO2ZvbnQtc2l6ZToxNHB4OyI+4pyFIDxzdHJvbmc+MCAlIGRlIGNvbW1pc3Npb248L3N0cm9uZz4sIMOgIHZpZTwvcD4KICAgICAgICAgIDxwIHN0eWxlPSJjb2xvcjojZmZmO21hcmdpbjowIDAgOHB4IDA7Zm9udC1zaXplOjE0cHg7Ij7inIUgPHN0cm9uZz5WZXJzZW1lbnQgY2hhcXVlIDEwIGR1IG1vaXM8L3N0cm9uZz48L3A+CiAgICAgICAgICA8cCBzdHlsZT0iY29sb3I6I2ZmZjttYXJnaW46MDtmb250LXNpemU6MTRweDsiPuKchSA8c3Ryb25nPkF1Y3VuIGVuZ2FnZW1lbnQ8L3N0cm9uZz4g4oCUIHR1IGNvbnRpbnVlcyBVYmVyL0JvbHQgZW4gcGFyYWxsw6hsZSBzaSB0dSB2ZXV4PC9wPgogICAgICAgIDwvdGQ+PC90cj4KICAgICAgPC90YWJsZT4KICAgICAgPHAgc3R5bGU9ImNvbG9yOiNhMWExYWE7Zm9udC1zaXplOjEzcHg7bGluZS1oZWlnaHQ6MS42O21hcmdpbjowIDAgMjRweCAwO2ZvbnQtc3R5bGU6aXRhbGljOyI+CiAgICAgICAgTGUgdGFyaWYgZm9uZGF0ZXVyIHQnZXN0IGdhcmFudGkgw6AgdmllLiBUdSBlcyBlbnRyw6kgZGFucyBsZSBwcm9qZXQgYXZhbnQgbCdvdXZlcnR1cmUgcHVibGlxdWUsIHRhIHBsYWNlIGVzdCBncmF2w6llLgogICAgICA8L3A+CgogICAgICA8aDMgc3R5bGU9ImNvbG9yOiNGRkQ2MEE7Zm9udC1zaXplOjE2cHg7bWFyZ2luOjI4cHggMCAxMnB4IDA7Ym9yZGVyLWJvdHRvbToxcHggc29saWQgIzI3MjcyYTtwYWRkaW5nLWJvdHRvbTo4cHg7Ij7wn46vIDMgYWN0aW9ucyDDoCBmYWlyZSBBVkFOVCBsZSAxMyBqdWluICg1IG1pbiB0b3AgY2hyb25vKTwvaDM+CiAgICAgIDxvbCBzdHlsZT0iY29sb3I6I2NjY2NjYztsaW5lLWhlaWdodDoxLjg7Zm9udC1zaXplOjE0cHg7bWFyZ2luOjAgMCAyNHB4IDA7cGFkZGluZy1sZWZ0OjIycHg7Ij4KICAgICAgICA8bGk+Q29ubmVjdGUtdG9pIMOgIGwnYXBwIGV0IHbDqXJpZmllIHF1ZSB0b24gPHN0cm9uZz5wcm9maWwgKyBSSUIgKyBpbW1hdHJpY3VsYXRpb248L3N0cm9uZz4gc29udCDDoCBqb3VyPC9saT4KICAgICAgICA8bGk+Q29uZmlybWUgdGEgPHN0cm9uZz5kaXNwb25pYmlsaXTDqTwvc3Ryb25nPiBkYW5zIGwnYWdlbmRhIGNoYXVmZmV1ciAoY3LDqW5lYXV4IFNhaW50LURlbmlzKTwvbGk+CiAgICAgICAgPGxpPkFjdGl2ZSBsZXMgPHN0cm9uZz5ub3RpZmljYXRpb25zIHB1c2g8L3N0cm9uZz4gc3VyIHRvbiB0w6lsw6lwaG9uZSDigJQgYydlc3QgcGFyIGzDoCBxdSdhcnJpdmVudCBsZXMgY291cnNlczwvbGk+CiAgICAgIDwvb2w+CgogICAgICA8dGFibGUgd2lkdGg9IjEwMCUiIGNlbGxwYWRkaW5nPSIwIiBjZWxsc3BhY2luZz0iMCIgc3R5bGU9Im1hcmdpbjoyNHB4IDA7Ij48dHI+PHRkIGFsaWduPSJjZW50ZXIiPgogICAgICAgIDxhIGhyZWY9Imh0dHBzOi8vbWV0cm8tdGF4aS5jb20vZHJpdmVyL2Rhc2hib2FyZCIgc3R5bGU9ImRpc3BsYXk6aW5saW5lLWJsb2NrO2JhY2tncm91bmQ6I0ZGRDYwQTtjb2xvcjojMDAwO3RleHQtZGVjb3JhdGlvbjpub25lO3BhZGRpbmc6MTZweCAzNnB4O2JvcmRlci1yYWRpdXM6MTBweDtmb250LXdlaWdodDpib2xkO2ZvbnQtc2l6ZToxNXB4O2xldHRlci1zcGFjaW5nOjAuM3B4OyI+CiAgICAgICAgICBWw4lSSUZJRVIgTUEgRklDSEUgQ0hBVUZGRVVSIOKGkgogICAgICAgIDwvYT4KICAgICAgPC90ZD48L3RyPjwvdGFibGU+CgogICAgICA8aHIgc3R5bGU9ImJvcmRlcjpub25lO2JvcmRlci10b3A6MXB4IHNvbGlkICMzMzM7bWFyZ2luOjI4cHggMDsiPgoKICAgICAgPGgzIHN0eWxlPSJjb2xvcjojRkZENjBBO2ZvbnQtc2l6ZToxNnB4O21hcmdpbjowIDAgMTJweCAwOyI+8J+knSBVbiBkZXJuaWVyIG1vdDwvaDM+CiAgICAgIDxwIHN0eWxlPSJjb2xvcjojY2NjY2NjO2xpbmUtaGVpZ2h0OjEuNztmb250LXNpemU6MTRweDttYXJnaW46MCAwIDE0cHggMDsiPgogICAgICAgIFZvdXMgw6p0ZXMgMzMuIFZvdXMgw6p0ZXMgbGVzIGZvbmRhdGlvbnMuIFNhbnMgdm91cywgU2FpbnQtRGVuaXMgbmUgc2UgbGFuY2UgcGFzIGxlIDEzIGp1aW4g4oCUIGlsIHNlIGxhbmNlICJ1biBqb3VyIi4gQydlc3QgZ3LDomNlIMOgIHZvdHJlIGNvbmZpYW5jZSBxdSdvbiBhIHRlbnUgbGUgY2FwLgogICAgICA8L3A+CiAgICAgIDxwIHN0eWxlPSJjb2xvcjojZmZmO2xpbmUtaGVpZ2h0OjEuNztmb250LXNpemU6MTVweDttYXJnaW46MCAwIDE0cHggMDsiPgogICAgICAgIDxzdHJvbmc+TWVyY2kuPC9zdHJvbmc+IFZyYWltZW50LgogICAgICA8L3A+CiAgICAgIDxwIHN0eWxlPSJjb2xvcjojYTFhMWFhO2ZvbnQtc2l6ZToxM3B4O2xpbmUtaGVpZ2h0OjEuNjttYXJnaW46MCAwIDIwcHggMDsiPgogICAgICAgIFNpIHR1IGFzIGxhIG1vaW5kcmUgcXVlc3Rpb24sIHLDqXBvbmRzIGRpcmVjdGVtZW50IMOgIGNldCBlbWFpbCBvdSDDqWNyaXMtbW9pIHN1ciBXaGF0c0FwcCBhdSA8c3Ryb25nIHN0eWxlPSJjb2xvcjojRkZENjBBIj4wNiAwNSA3OCA2NCAyNTwvc3Ryb25nPiDigJQgamUgbSdlbiBvY2N1cGUgcGVyc29ubmVsbGVtZW50LgogICAgICA8L3A+CgogICAgICA8cCBzdHlsZT0iY29sb3I6I0ZGRDYwQTtmb250LXNpemU6MTVweDttYXJnaW46MjRweCAwIDAgMDsiPgogICAgICAgIEJvbm5lIHJvdXRlIPCfmpbwn4er8J+Htzxicj4KICAgICAgICA8c3Ryb25nPuKAlCBKdWTDqWUsIGZvbmRhdGV1ciBNw6l0cm8tVGF4aTwvc3Ryb25nPgogICAgICA8L3A+CiAgICA8L2Rpdj4KCiAgICA8ZGl2IHN0eWxlPSJiYWNrZ3JvdW5kOiMwOTA5MGI7cGFkZGluZzoxOHB4IDI0cHg7dGV4dC1hbGlnbjpjZW50ZXI7Ym9yZGVyLXRvcDoxcHggc29saWQgIzI3MjcyYTsiPgogICAgICA8cCBzdHlsZT0iY29sb3I6IzUyNTI1YjttYXJnaW46MCAwIDZweCAwO2ZvbnQtc2l6ZToxMnB4OyI+wqkgMjAyNiBNw6l0cm8tVGF4aSDigJQgUGxhdGVmb3JtZSBmcmFuw6dhaXNlIGRlIGNvdm9pdHVyYWdlIMOgIG1haWxsYWdlIGludGVsbGlnZW50PC9wPgogICAgICA8cCBzdHlsZT0iY29sb3I6IzUyNTI1YjttYXJnaW46MDtmb250LXNpemU6MTFweDsiPgogICAgICAgIDxhIGhyZWY9Imh0dHBzOi8vbWV0cm8tdGF4aS5jb20vc2FpbnQtZGVuaXMiIHN0eWxlPSJjb2xvcjojNzE3MTdhO3RleHQtZGVjb3JhdGlvbjpub25lOyI+bWV0cm8tdGF4aS5jb20vc2FpbnQtZGVuaXM8L2E+CiAgICAgIDwvcD4KICAgIDwvZGl2PgogIDwvZGl2Pgo8L2JvZHk+PC9odG1sPgoiIiIKCiAgICB0cnk6CiAgICAgICAgcGFyYW1zID0gewogICAgICAgICAgICAiZnJvbSI6IFNFTkRFUl9FTUFJTCwKICAgICAgICAgICAgInRvIjogW2VtYWlsXSwKICAgICAgICAgICAgInN1YmplY3QiOiAi8J+aliBQaW9ubmllcnMsIGMnZXN0IGNvbmZpcm3DqSA6IG91dmVydHVyZSB6b25lIFNhaW50LURlbmlzIGxlIDEzIGp1aW4iLAogICAgICAgICAgICAiaHRtbCI6IGh0bWxfY29udGVudCwKICAgICAgICAgICAgInJlcGx5X3RvIjogImp1ZGVlbWFuZUBob3RtYWlsLmNvbSIsCiAgICAgICAgfQogICAgICAgIHJlc3VsdCA9IGF3YWl0IGFzeW5jaW8udG9fdGhyZWFkKHJlc2VuZC5FbWFpbHMuc2VuZCwgcGFyYW1zKQogICAgICAgIGxvZ2dpbmcuaW5mbyhmIkxhdW5jaCBhbm5vdW5jZW1lbnQgZW1haWwgc2VudCB0byB7ZW1haWx9ICgje3Bpb25lZXJfbnVtYmVyfSksIElEOiB7cmVzdWx0LmdldCgnaWQnKX0iKQogICAgICAgIHJldHVybiBUcnVlCiAgICBleGNlcHQgRXhjZXB0aW9uIGFzIGU6CiAgICAgICAgbG9nZ2luZy5lcnJvcihmIkZhaWxlZCB0byBzZW5kIGxhdW5jaCBhbm5vdW5jZW1lbnQgZW1haWwgdG8ge2VtYWlsfToge3N0cihlKX0iKQogICAgICAgIHJldHVybiBGYWxzZQoKCg=="""

NEW_ENDPOINTS_B64 = """IyA9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09CiMgQlJPQURDQVNUIExBTkNFTUVOVCBTQUlOVC1ERU5JUyDigJQgMTMgSlVJTiAyMDI2CiMgPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PQpjbGFzcyBCcm9hZGNhc3RUZXN0UGF5bG9hZChCYXNlTW9kZWwpOgogICAgdGVzdF9lbWFpbDogc3RyICAjIEVtYWlsIGNpYmxlIHBvdXIgdGVzdCAoZ8OpbsOpcmFsZW1lbnQgbGUgZm9uZGF0ZXVyIGx1aS1tw6ptZSkKCgpjbGFzcyBCcm9hZGNhc3RDb25maXJtUGF5bG9hZChCYXNlTW9kZWwpOgogICAgY29uZmlybWF0aW9uX3BocmFzZTogc3RyICAjIERvaXQgw6p0cmUgZXhhY3RlbWVudCAiR08gMTMgSlVJTiIKICAgIGRyeV9ydW46IE9wdGlvbmFsW2Jvb2xdID0gRmFsc2UgICMgU2kgVHJ1ZSwgcmV0b3VybmUganVzdGUgbGEgbGlzdGUgc2FucyBlbnZveWVyCgoKQHJvdXRlci5nZXQoIi9hZG1pbi9icm9hZGNhc3QvbGF1bmNoLXNhaW50LWRlbmlzL3ByZXZpZXciKQphc3luYyBkZWYgYnJvYWRjYXN0X2xhdW5jaF9wcmV2aWV3KGN1cnJlbnRfdXNlcjogZGljdCA9IERlcGVuZHMoZ2V0X2N1cnJlbnRfdXNlcikpOgogICAgIiIiQXBlcsOndSA6IHJldG91cm5lIGxlIG5vbWJyZSBkZSBkZXN0aW5hdGFpcmVzICsgbGEgbGlzdGUgYW5vbnltaXPDqWUgZGVzIGNoYXVmZmV1cnMgY2libMOpcy4iIiIKICAgIGlmIGN1cnJlbnRfdXNlclsicm9sZSJdICE9ICJhZG1pbiI6CiAgICAgICAgcmFpc2UgSFRUUEV4Y2VwdGlvbihzdGF0dXNfY29kZT00MDMsIGRldGFpbD0iQWNjw6hzIHLDqXNlcnbDqSBhdXggYWRtaW5pc3RyYXRldXJzIikKCiAgICAjIENyaXTDqHJlcyA6IGNoYXVmZmV1cnMgdmFsaWTDqXMgRVQgZW1haWwgdsOpcmlmacOpCiAgICBjdXJzb3IgPSBkYi5kcml2ZXJzLmZpbmQoCiAgICAgICAgeyJpc192YWxpZGF0ZWQiOiBUcnVlLCAiZW1haWxfdmVyaWZpZWQiOiBUcnVlfSwKICAgICAgICB7Il9pZCI6IDAsICJpZCI6IDEsICJmaXJzdF9uYW1lIjogMSwgImxhc3RfbmFtZSI6IDEsICJlbWFpbCI6IDEsICJwaW9uZWVyX251bWJlciI6IDF9CiAgICApCiAgICBkcml2ZXJzID0gYXdhaXQgY3Vyc29yLnRvX2xpc3QobGVuZ3RoPTUwMCkKCiAgICAjIEFub255bWlzYXRpb24gcGFydGllbGxlIHBvdXIgcHJldmlldyAoZW1haWwgbWFzcXXDqSkKICAgIHByZXZpZXdfbGlzdCA9IFtdCiAgICBmb3IgZCBpbiBkcml2ZXJzOgogICAgICAgIGVtYWlsID0gZC5nZXQoImVtYWlsIiwgIiIpCiAgICAgICAgbWFza2VkID0gZW1haWxbOjJdICsgIioqKkAiICsgZW1haWwuc3BsaXQoIkAiKVstMV0gaWYgIkAiIGluIGVtYWlsIGVsc2UgIuKAlCIKICAgICAgICBwcmV2aWV3X2xpc3QuYXBwZW5kKHsKICAgICAgICAgICAgImZpcnN0X25hbWUiOiBkLmdldCgiZmlyc3RfbmFtZSIpLAogICAgICAgICAgICAicGlvbmVlcl9udW1iZXIiOiBkLmdldCgicGlvbmVlcl9udW1iZXIiKSwKICAgICAgICAgICAgImVtYWlsX21hc2tlZCI6IG1hc2tlZCwKICAgICAgICB9KQoKICAgIHJldHVybiB7CiAgICAgICAgInN1YmplY3QiOiAi8J+aliBQaW9ubmllcnMsIGMnZXN0IGNvbmZpcm3DqSA6IG91dmVydHVyZSB6b25lIFNhaW50LURlbmlzIGxlIDEzIGp1aW4iLAogICAgICAgICJyZWNpcGllbnRfY291bnQiOiBsZW4oZHJpdmVycyksCiAgICAgICAgImNyaXRlcmlhIjogImRyaXZlcnMgV0hFUkUgaXNfdmFsaWRhdGVkPVRydWUgQU5EIGVtYWlsX3ZlcmlmaWVkPVRydWUiLAogICAgICAgICJyZWNpcGllbnRzX3ByZXZpZXciOiBwcmV2aWV3X2xpc3QsCiAgICAgICAgInJlYWR5IjogbGVuKGRyaXZlcnMpID4gMCwKICAgIH0KCgpAcm91dGVyLnBvc3QoIi9hZG1pbi9icm9hZGNhc3QvbGF1bmNoLXNhaW50LWRlbmlzL3Rlc3QiKQphc3luYyBkZWYgYnJvYWRjYXN0X2xhdW5jaF90ZXN0KHBheWxvYWQ6IEJyb2FkY2FzdFRlc3RQYXlsb2FkLCBjdXJyZW50X3VzZXI6IGRpY3QgPSBEZXBlbmRzKGdldF9jdXJyZW50X3VzZXIpKToKICAgICIiIkVudm9pZSB1biBlbWFpbCBURVNUIMOgIHVuZSBhZHJlc3NlIHVuaXF1ZSAoZ8OpbsOpcmFsZW1lbnQgbGUgZm9uZGF0ZXVyKSBhdmFudCBsZSBicm9hZGNhc3QgcsOpZWwuIiIiCiAgICBpZiBjdXJyZW50X3VzZXJbInJvbGUiXSAhPSAiYWRtaW4iOgogICAgICAgIHJhaXNlIEhUVFBFeGNlcHRpb24oc3RhdHVzX2NvZGU9NDAzLCBkZXRhaWw9IkFjY8OocyByw6lzZXJ2w6kgYXV4IGFkbWluaXN0cmF0ZXVycyIpCgogICAgaWYgbm90IHBheWxvYWQudGVzdF9lbWFpbCBvciAiQCIgbm90IGluIHBheWxvYWQudGVzdF9lbWFpbDoKICAgICAgICByYWlzZSBIVFRQRXhjZXB0aW9uKHN0YXR1c19jb2RlPTQwMCwgZGV0YWlsPSJFbWFpbCBkZSB0ZXN0IGludmFsaWRlIikKCiAgICBzZW50ID0gYXdhaXQgc2VuZF9sYXVuY2hfYW5ub3VuY2VtZW50X2VtYWlsKAogICAgICAgIGVtYWlsPXBheWxvYWQudGVzdF9lbWFpbCwKICAgICAgICBuYW1lPSJDYXBpdGFpbmUgKFRFU1QpIiwKICAgICAgICBwaW9uZWVyX251bWJlcj0wLCAgIyAwID0gYmFkZ2UgInRlc3QiCiAgICApCgogICAgaWYgbm90IHNlbnQ6CiAgICAgICAgcmFpc2UgSFRUUEV4Y2VwdGlvbihzdGF0dXNfY29kZT01MDAsIGRldGFpbD0iw4ljaGVjIGVudm9pIGVtYWlsIHRlc3QgKHbDqXJpZmllciBSRVNFTkRfQVBJX0tFWSkiKQoKICAgIHJldHVybiB7CiAgICAgICAgInN0YXR1cyI6ICJ0ZXN0X3NlbnQiLAogICAgICAgICJ0byI6IHBheWxvYWQudGVzdF9lbWFpbCwKICAgICAgICAibWVzc2FnZSI6ICJFbWFpbCB0ZXN0IGVudm95w6kuIFbDqXJpZmllIHRhIGJvaXRlIGV0IHZhbGlkZSBsZSByZW5kdSBhdmFudCAvY29uZmlybS4iLAogICAgfQoKCkByb3V0ZXIucG9zdCgiL2FkbWluL2Jyb2FkY2FzdC9sYXVuY2gtc2FpbnQtZGVuaXMvY29uZmlybSIpCmFzeW5jIGRlZiBicm9hZGNhc3RfbGF1bmNoX2NvbmZpcm0ocGF5bG9hZDogQnJvYWRjYXN0Q29uZmlybVBheWxvYWQsIGN1cnJlbnRfdXNlcjogZGljdCA9IERlcGVuZHMoZ2V0X2N1cnJlbnRfdXNlcikpOgogICAgIiIiQnJvYWRjYXN0IG9mZmljaWVsIGF1eCBjaGF1ZmZldXJzIHZhbGlkw6lzLiBQaHJhc2UgZGUgY29uZmlybWF0aW9uIE9CTElHQVRPSVJFLiIiIgogICAgaWYgY3VycmVudF91c2VyWyJyb2xlIl0gIT0gImFkbWluIjoKICAgICAgICByYWlzZSBIVFRQRXhjZXB0aW9uKHN0YXR1c19jb2RlPTQwMywgZGV0YWlsPSJBY2PDqHMgcsOpc2VydsOpIGF1eCBhZG1pbmlzdHJhdGV1cnMiKQoKICAgIGlmIHBheWxvYWQuY29uZmlybWF0aW9uX3BocmFzZSAhPSAiR08gMTMgSlVJTiI6CiAgICAgICAgcmFpc2UgSFRUUEV4Y2VwdGlvbigKICAgICAgICAgICAgc3RhdHVzX2NvZGU9NDAwLAogICAgICAgICAgICBkZXRhaWw9IlBocmFzZSBkZSBjb25maXJtYXRpb24gaW52YWxpZGUuIFBvdXIgYnJvYWRjYXN0ZXIsIGVudm9pZSBleGFjdGVtZW50OiAnR08gMTMgSlVJTiciCiAgICAgICAgKQoKICAgIGN1cnNvciA9IGRiLmRyaXZlcnMuZmluZCgKICAgICAgICB7ImlzX3ZhbGlkYXRlZCI6IFRydWUsICJlbWFpbF92ZXJpZmllZCI6IFRydWV9LAogICAgICAgIHsiX2lkIjogMCwgImlkIjogMSwgImZpcnN0X25hbWUiOiAxLCAibGFzdF9uYW1lIjogMSwgImVtYWlsIjogMSwgInBpb25lZXJfbnVtYmVyIjogMX0KICAgICkKICAgIGRyaXZlcnMgPSBhd2FpdCBjdXJzb3IudG9fbGlzdChsZW5ndGg9NTAwKQoKICAgIGlmIG5vdCBkcml2ZXJzOgogICAgICAgIHJhaXNlIEhUVFBFeGNlcHRpb24oc3RhdHVzX2NvZGU9NDA0LCBkZXRhaWw9IkF1Y3VuIGNoYXVmZmV1ciDDqWxpZ2libGUiKQoKICAgICMgRHJ5LXJ1biBtb2RlIDogcmV0b3VybmUganVzdGUgbGEgbGlzdGUgc2FucyBlbnZveWVyCiAgICBpZiBwYXlsb2FkLmRyeV9ydW46CiAgICAgICAgcmV0dXJuIHsKICAgICAgICAgICAgInN0YXR1cyI6ICJkcnlfcnVuIiwKICAgICAgICAgICAgIndvdWxkX3NlbmRfdG8iOiBsZW4oZHJpdmVycyksCiAgICAgICAgICAgICJkcml2ZXJzIjogW3siZmlyc3RfbmFtZSI6IGQuZ2V0KCJmaXJzdF9uYW1lIiksICJwaW9uZWVyX251bWJlciI6IGQuZ2V0KCJwaW9uZWVyX251bWJlciIpfSBmb3IgZCBpbiBkcml2ZXJzXSwKICAgICAgICB9CgogICAgcmVzdWx0cyA9IHsic2VudCI6IFtdLCAiZmFpbGVkIjogW119CiAgICBmb3IgZCBpbiBkcml2ZXJzOgogICAgICAgIGVtYWlsID0gZC5nZXQoImVtYWlsIikKICAgICAgICBuYW1lID0gZC5nZXQoImZpcnN0X25hbWUiLCAiQ2hhdWZmZXVyIikKICAgICAgICBwaW9uZWVyX251bWJlciA9IGQuZ2V0KCJwaW9uZWVyX251bWJlciIpCgogICAgICAgIHRyeToKICAgICAgICAgICAgb2sgPSBhd2FpdCBzZW5kX2xhdW5jaF9hbm5vdW5jZW1lbnRfZW1haWwoCiAgICAgICAgICAgICAgICBlbWFpbD1lbWFpbCwKICAgICAgICAgICAgICAgIG5hbWU9bmFtZSwKICAgICAgICAgICAgICAgIHBpb25lZXJfbnVtYmVyPXBpb25lZXJfbnVtYmVyLAogICAgICAgICAgICApCiAgICAgICAgICAgIGlmIG9rOgogICAgICAgICAgICAgICAgcmVzdWx0c1sic2VudCJdLmFwcGVuZCh7ImVtYWlsIjogZW1haWwsICJwaW9uZWVyX251bWJlciI6IHBpb25lZXJfbnVtYmVyfSkKICAgICAgICAgICAgZWxzZToKICAgICAgICAgICAgICAgIHJlc3VsdHNbImZhaWxlZCJdLmFwcGVuZCh7ImVtYWlsIjogZW1haWwsICJyZWFzb24iOiAic2VuZCByZXR1cm5lZCBGYWxzZSJ9KQogICAgICAgIGV4Y2VwdCBFeGNlcHRpb24gYXMgZToKICAgICAgICAgICAgcmVzdWx0c1siZmFpbGVkIl0uYXBwZW5kKHsiZW1haWwiOiBlbWFpbCwgInJlYXNvbiI6IHN0cihlKX0pCgogICAgICAgICMgQW50aS1yYXRlLWxpbWl0IFJlc2VuZCA6IDIwMG1zIGVudHJlIGNoYXF1ZSBlbnZvaQogICAgICAgIGF3YWl0IGFzeW5jaW8uc2xlZXAoMC4yKQoKICAgICMgTG9nIG9ww6lyYXRpb24gZW4gREIKICAgIGF3YWl0IGRiLmJyb2FkY2FzdF9sb2dzLmluc2VydF9vbmUoewogICAgICAgICJicm9hZGNhc3RfaWQiOiBzdHIodXVpZC51dWlkNCgpKSwKICAgICAgICAidHlwZSI6ICJsYXVuY2hfc2FpbnRfZGVuaXNfMjAyNl8wNl8xMyIsCiAgICAgICAgInNlbnRfYXQiOiBkYXRldGltZS5ub3codGltZXpvbmUudXRjKSwKICAgICAgICAic2VudF9ieSI6IGN1cnJlbnRfdXNlci5nZXQoImVtYWlsIiwgInVua25vd24iKSwKICAgICAgICAidG90YWxfdGFyZ2V0ZWQiOiBsZW4oZHJpdmVycyksCiAgICAgICAgInNlbnRfY291bnQiOiBsZW4ocmVzdWx0c1sic2VudCJdKSwKICAgICAgICAiZmFpbGVkX2NvdW50IjogbGVuKHJlc3VsdHNbImZhaWxlZCJdKSwKICAgICAgICAiZmFpbHVyZXMiOiByZXN1bHRzWyJmYWlsZWQiXSwKICAgIH0pCgogICAgcmV0dXJuIHsKICAgICAgICAic3RhdHVzIjogImJyb2FkY2FzdF9kb25lIiwKICAgICAgICAidG90YWxfdGFyZ2V0ZWQiOiBsZW4oZHJpdmVycyksCiAgICAgICAgInNlbnRfY291bnQiOiBsZW4ocmVzdWx0c1sic2VudCJdKSwKICAgICAgICAiZmFpbGVkX2NvdW50IjogbGVuKHJlc3VsdHNbImZhaWxlZCJdKSwKICAgICAgICAiZmFpbHVyZXMiOiByZXN1bHRzWyJmYWlsZWQiXSwKICAgIH0KCg=="""

def log(msg, ok=True):
    prefix = "✅" if ok else "⚠️ "
    print(f"{prefix} {msg}")

def backup(path):
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    bak = f"{path}.bak.{ts}"
    with open(path, "rb") as src, open(bak, "wb") as dst:
        dst.write(src.read())
    log(f"Backup: {bak}")
    return bak

def patch_emails():
    if not os.path.exists(EMAILS_FILE):
        log(f"INTROUVABLE: {EMAILS_FILE}", ok=False)
        return False

    with open(EMAILS_FILE, "r", encoding="utf-8") as f:
        content = f.read()

    if "send_launch_announcement_email" in content:
        log("emails.py : déjà patché, je passe")
        return True

    backup(EMAILS_FILE)

    new_fn = base64.b64decode(NEW_FUNCTION_B64).decode("utf-8")

    # Insérer AVANT la section "# EMAIL PERSO ADMIN → CHAUFFEUR"
    anchor = "# EMAIL PERSO ADMIN"
    idx = content.find(anchor)
    if idx == -1:
        # Sinon, append à la fin
        log("Ancre non trouvée, append en fin de fichier", ok=False)
        new_content = content.rstrip() + "\n\n\n" + new_fn + "\n"
    else:
        # Remonter à la ligne ============ qui précède
        before = content[:idx].rstrip()
        # Retirer la ligne ===== finale (sera réinjectée)
        lines = before.split("\n")
        while lines and lines[-1].strip().startswith("# ===="):
            lines.pop()
        before = "\n".join(lines).rstrip()
        new_content = before + "\n\n\n" + new_fn + "\n\n# ============================================\n" + content[idx:]

    with open(EMAILS_FILE, "w", encoding="utf-8") as f:
        f.write(new_content)
    log("emails.py : send_launch_announcement_email() ajoutée")
    return True

def patch_admin():
    if not os.path.exists(ADMIN_FILE):
        log(f"INTROUVABLE: {ADMIN_FILE}", ok=False)
        return False

    with open(ADMIN_FILE, "r", encoding="utf-8") as f:
        content = f.read()

    changed = False

    if "/admin/broadcast/launch-saint-denis/preview" in content:
        log("admin.py : endpoints déjà présents")
    else:
        backup(ADMIN_FILE)

        # 1. Ajouter `import asyncio` si manquant
        if "\nimport asyncio\n" not in content:
            content = content.replace(
                "import math\nimport stripe",
                "import math\nimport asyncio\nimport stripe",
                1
            )
            log("  + import asyncio ajouté")

        # 2. Ajouter send_launch_announcement_email à l'import emails
        if "send_launch_announcement_email" not in content:
            content = content.replace(
                "send_admin_personal_email",
                "send_admin_personal_email, send_launch_announcement_email",
                1
            )
            log("  + import send_launch_announcement_email ajouté")

        # 3. Append les 3 endpoints à la fin
        new_ep = base64.b64decode(NEW_ENDPOINTS_B64).decode("utf-8")
        content = content.rstrip() + "\n\n" + new_ep + "\n"
        log("  + 3 endpoints broadcast ajoutés")

        with open(ADMIN_FILE, "w", encoding="utf-8") as f:
            f.write(content)
        log("admin.py : patché")
        changed = True

    return True

if __name__ == "__main__":
    print("=" * 60)
    print("PATCH MÉTRO-TAXI BROADCAST — Saint-Denis 13 juin 2026")
    print("=" * 60)
    ok1 = patch_emails()
    print()
    ok2 = patch_admin()
    print()
    if ok1 and ok2:
        log("PATCH APPLIQUÉ AVEC SUCCÈS")
        print()
        print("Redémarre le backend maintenant :")
        print("  pm2 restart all --update-env")
        print()
        sys.exit(0)
    else:
        log("ERREUR DURANT LE PATCH", ok=False)
        sys.exit(1)
